name: Test drive Github Actions
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Explore
        uses: docker://alpine:3
        with:
          entrypoint: /bin/sh
          args: -c "apk add --no-cache tree && tree"
