name: Test drive Github Actions
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bookish-octo-spoon
        uses: actions/checkout@v2
        with:
          path: bookish-octo-spoon
      - name: Checkout fictional-octo-eureka
        uses: actions/checkout@v2
        with:
          repository: pkumar0508/fictional-octo-eureka
          path: fictional-octo-eureka
      - name: Explore
        uses: docker://alpine:3
        with:
          entrypoint: /bin/sh
          args: -c "apk add --no-cache tree && tree"
      - name: Generate new file
        run: sha256sum bookish-octo-spoon/panda > fictional-octo-eureka/forever
